eureka:
  instance:
      metadata-map:
        instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi
  boot:
    admin:
      client:
        enabled: true
      url: http://localhost:8070

